name: egret_env
channels:
  - conda-forge
  - r
  - bioconda
  - defaults
dependencies:
  # R packages
  - r-base>=4.1
  - r-r.utils
  - r-data.table
  - r-wgcna
  - r-optparse
  - r-rcppeigen
  - r-glmnet
  - r-matrixeqtl
  - r-devtools
  - r-tidyr
  - r-mclust
  - r-ggplot2
